### PR TITLE
Parse emails with \n newlines if they don't contain binary content

### LINKED ISSUE #1129: LF emails can't be parsed anymore
removed in #1113 / master branch

I have many eml files in my specs with just LF separator, that passes on 2.6.6 stable
```
HEADER
LFLF
BODY
```

when normalization was removed, header separator doesn't work with it anymore, the parser thinks that the whole email is a header which is wrong.
```
HEADER_SEPARATOR = /#{CRLF}#{CRLF}/
```

according to the RFC, header separator should be always 2x CRLF
https://www.ietf.org/rfc/rfc2822.txt

so my question is, should eml files with just LF separators be parsable or not?
It doesn't comply with RFC, but standard mail clients like Outlook or Thunderbird can open and work with these files just fine. It also used to work with mail 2.6.6.

### PR DESCRIPTION
**Pull request by jeremy**
Binary-safe newline conversion ensures that attachments don't get corrupted. Requires that text is ASCII-only.

Fixes #1129
References #1113

### CODE REVIEW

File: lib/mail/encodings/7bit.rb [hunk 1]
```diff
@@ -4,29 +4,19 @@
...
-      # Encode the string
+
       def self.encode(str)
-        super
-      end
-     
-      # Idenity encodings have a fixed cost, 1 byte out per 1 byte in
-      def self.cost(str)
-        super 
+        ::Mail::Utilities.binary_unsafe_to_crlf str
```
Comment (jeremy) [inline lib/mail/encodings/7bit.rb]: 7bit encoding → never binary

File: lib/mail/encodings/base64.rb [hunk 2]
```diff
@@ -4,36 +4,35 @@
...
-      # Decode the string from Base64
       def self.decode(str)
-        RubyVer.decode_base64( str )
+        RubyVer.decode_base64(str)
       end
 
-      # Encode the string to Base64
       def self.encode(str)
-        ::Mail::Utilities.to_crlf(RubyVer.encode_base64( str ))
+        ::Mail::Utilities.binary_unsafe_to_crlf(RubyVer.encode_base64(str))
```
Comment (jeremy) [inline lib/mail/encodings/base64.rb]: Base64 is 7bit ASCII, ok to convert newlines

File: lib/mail/encodings/8bit.rb [hunk 3]
```diff
@@ -6,32 +6,13 @@ module Mail
...
-      
-      # Decode the string
-      def self.decode(str)
-        ::Mail::Utilities.to_lf str
-      end
-    
-      # Encode the string
-      def self.encode(str)
-        ::Mail::Utilities.to_crlf str
-      end
```
Comment (jeremy) [inline lib/mail/encodings/8bit.rb]: No longer performing newline conversion in 8bit/binary encodings

File: lib/mail/network/delivery_methods/sendmail.rb [hunk 4]
```diff
@@ -61,7 +61,7 @@ def deliver!(mail)
 
     def self.call(path, arguments, destinations, encoded_message)
       popen "#{path} #{arguments} #{destinations}" do |io|
-        io.puts ::Mail::Utilities.to_lf(encoded_message)
+        io.puts ::Mail::Utilities.binary_unsafe_to_lf(encoded_message)
```
Comment (jeremy) [inline lib/mail/network/delivery_methods/sendmail.rb]: Encoded message is 7bit ASCII, safe to convert newlines for `sendmail` (which expects LF newlines)

File: lib/mail/utilities.rb [hunk 5]
```diff
@@ -248,33 +248,62 @@ def map_with_index( enum, &block )
...
+    # encoding 8bit and base64 Content-Transfer-Encoding and for convenience
+    # when parsing emails with \n line endings instead of the required \r\n.
+    def self.to_crlf(string)
+      string = string.to_s
+      if safe_for_line_ending_conversion? string
+        binary_unsafe_to_crlf string
+      else
+        string
+      end
     end
```
Comment (jeremy) [inline lib/mail/utilities.rb]: `to_lf` and `to_crlf` are now "best attempt" converters. If the string is unsafe for conversion, they aren't modified.

File: spec/mail/body_spec.rb [hunk 6]
```diff
@@ -443,7 +443,7 @@ def assert_split_into(body, pre, epi, parts)
 
   describe "non US-ASCII charset" do
     it "should encoded" do
-      body = Mail::Body.new("あいうえお\n")
+      body = Mail::Body.new("あいうえお\r\n")
```
Comment (jeremy) [inline spec/mail/body_spec.rb]: Since non-ASCII chars are seen as possibly-binary. We could improve the heuristic to check for other valid text encodings to allow this.

**Comment by dalibor** [comment]
@jeremy Thanks for the recent bug fixes and the 2.7.0.rc2 release! I ran my test suite with it and the only thing I'm seeing are few examples where this LF to CRLF conversion is not applied when parsing emails (see below). Using the `Mail::Utilities.binary_unsafe_to_crlf` helper I'm able to fix my email source fixtures, so that's good.

1) Header / body CRLF split by `Mail::Message::HEADER_SEPARATOR`

```ruby
$ irb
>> gem 'mail', '2.6.6'; require 'mail'
=> true
>> Mail.new("Subject: Subject\n\nContent").body.decoded
=> "Content"
```

vs

```ruby
$ irb
>> gem 'mail', '2.7.0.rc2'; require 'mail'
=> true
>> Mail.new("Subject: Subject\n\nContent").body.decoded
=> ""
```

2) Using mail parts:

```ruby
$ irb
>> gem 'mail', '2.6.6'; require 'mail'
=> true
>> m1 = Mail.new; m1.text_part = Mail::Part.new('text'); m2 = Mail.new(m1.to_s.gsub("\r\n", "\n")); m2.text_part.decoded
=> "text"
```

vs

```ruby
$ irb
>> gem 'mail', '2.7.0.rc2'; require 'mail'
=> true
>> m1 = Mail.new; m1.text_part = Mail::Part.new('text'); m2 = Mail.new(m1.to_s.gsub("\r\n", "\n")); m2.text_part.decoded
NoMethodError: undefined method `decoded' for nil:NilClass
```

It fails because no text part was detected due to no proper CRLF in that source.

Not sure if this PR is intended to cover the above two cases, just wanted to bring it up here.

Thanks!

**Comment by jeremy** [comment]
Thanks @dalibor! I'll look at supporting these cases too 👍

**Comment by jeremy** [comment]
@dalibor fixed @ #1160

**Comment by dalibor** [comment]
@jeremy Thanks, latest patch works perfectly!

I'll do more tests in prod with 2.7.0.rc3 in the following days.
